# Script to load in symbolic regression expressions and compare against AIDA data sets
import numpy as np
from scipy.integrate import ode
from scipy import optimize
import scipy.special as sc
import matplotlib.pyplot as plt
import sys
import time as clock
import warnings
import functools
import os
import math

import pandas as pd
warnings.filterwarnings('ignore')	# Suppress Warnings generated by vectorized calculation of capacitance.

from data_utils import loadinitialcond, loadIWC, loadaidainputs
from constants import constants, labConfig
from aida_microphysics import getDepCoeffs, vecCapacitance, e_si
from plotting import makeAIDAExpoverviewplot


def compareAIDAexps(explist, newG, eqn):
    parceloutputs_all = []
    eqn = int(eqn)
    dir = "AIDAoutput/{}_Eq{:02d}".format(newG.name, eqn)
    print(dir)

    for exp in explist:
        m = 1.0
        expn = int(exp)

        initR = 0.75  # um
        stdDev = 0.15  # um
        rad = initR * 1.0e-6
        stdDev = stdDev * 1.0e-6

        observations = loadIWC(expn)
        inputs = loadaidainputs(expn)
        # # initialize the model
        capmodel = False
        # initialize the model
        # AIDAparcel = AIDAModel(capmodel=capmodel,newG=newG,m=m,inRadius=rad,inSD=stdDev,eqnidx=eqn)
        AIDAparcel = AIDAModel(capmodel=capmodel, newG=newG, m=m, inRadius=rad, inSD=stdDev, eqnidx=eqn,verbose=False)

        # integrate the time loop
        time, qv_out, si_out, r_out, a_out, c_out, integratedIce, IWC, Tout, Pout, qi_out, results, nBinsUsed = AIDAparcel.timeloop(
            expn)

        parceloutputs = np.zeros((10, qv_out.shape[0]))
        parceloutputs[0, :] = qv_out
        parceloutputs[1, :] = si_out
        parceloutputs[2, :] = r_out
        parceloutputs[3, :] = a_out
        parceloutputs[4, :] = c_out
        parceloutputs[5, :] = integratedIce
        parceloutputs[6, :] = IWC
        parceloutputs[7, :] = Tout
        parceloutputs[8, :] = Pout
        parceloutputs[9, :] = qi_out

        parceloutputs_all.append(parceloutputs)

        if not os.path.exists(dir):
            os.makedirs(dir)

        overviewname = os.path.join(dir, "Overview_Exp{:02d}".format(expn) + ".png")
        icebinsname = os.path.join(dir, "IceBins_Exp{:02d}".format(expn) + ".png")
        npname = os.path.join(dir, "Output_Exp{:02d}".format(expn) + ".npy")

        np.save(npname, parceloutputs)
        makeAIDAExpoverviewplot(overviewname, parceloutputs, inputs, observations, nBinsUsed, savefig=True)
    return parceloutputs_all

class AIDAModel(object):
    def __init__(self, capmodel=True, newG=None, eqnidx=4, m=1, inRadius=0.75e-6, inSD=0.15e-6, printtimes=False,verbose=True):
        # observations in AIDA (inputs to the model)
        self.cn_ice = np.zeros(1201)
        self.T = np.zeros(1201)
        self.p = np.zeros(1201)
        self.wallflux = np.zeros(1201)

        # depositional growth parameters
        self.m = m
        self.useFixedScrits = False
        self.fixedScrits = [0.10, 0.05]  # sca, scc
        self.useGG = False
        self.capmodel = capmodel
        self.newG = newG #(eqnidx=eqnidx)
        self.eqnidx = eqnidx
        self.printtimes = printtimes
        self.verbose = verbose

        # fixed Scrit
        self.sca = 0.10
        self.scc = 0.05

        # nucleation
        self.inRadius = inRadius  # Fixed initial radius or mean for gamma distribution (meters).
        self.inSD = inSD  # Standard deviation (meters) for gamma distribution.
        self.variance = self.inSD ** 2
        self.scale = self.variance / self.inRadius
        self.shape = self.inRadius / self.scale

        # model parameters
        self.dt = 1
        self.nbice = 700  # max. number of ice bins
        self.nIceBinsUsed = 0  # number of ice bins used
        self.tmax = 10  # len(self.cn_ice) - 1  # Maximum time [s].
        self.npts = int(self.tmax / self.dt)  # Number of time steps.

        # ice bin parameters for current time step
        self.Nice = np.zeros(self.nbice)  # Ice distribution.
        self.rice = np.zeros(self.nbice)  # Ice radii.
        self.a = np.zeros(self.nbice)
        self.c = np.zeros(self.nbice)
        self.v = np.zeros(self.nbice)
        self.phi = np.zeros(self.nbice)
        self.alpha_a = np.zeros(self.nbice)
        self.alpha_c = np.zeros(self.nbice)
        self.slocal_a = np.zeros(self.nbice)
        self.slocal_c = np.zeros(self.nbice)

    def nucleation(self, time, Si):
        nIceBinsUsed = self.nIceBinsUsed
        cn_ice = self.cn_ice
        dt = self.dt
        # rho_air = press/(Rd * temp)

        ndiff = cn_ice[int(time)] - cn_ice[int(time - dt)]  # increase in observed ice at this time step
        if ndiff > 0.0 and Si > 1.0:
            self.Nice[nIceBinsUsed] = ndiff  # /rho_air
            if (labConfig.gammaDist):
                self.rice[nIceBinsUsed] = np.random.gamma(self.shape, self.scale, 1)
            else:
                self.rice[nIceBinsUsed] = self.inRadius
            self.a[nIceBinsUsed] = self.rice[nIceBinsUsed]  # Initialize a-semiaxis.
            self.c[nIceBinsUsed] = self.rice[nIceBinsUsed]  # Initialize c-semiaxis.
            self.v[nIceBinsUsed] = (4.0 / 3.0) * np.pi * self.rice[nIceBinsUsed] ** 3
            self.phi[nIceBinsUsed] = self.c[nIceBinsUsed] / self.a[nIceBinsUsed]
            self.nIceBinsUsed = nIceBinsUsed + 1

    def dydt(self, t, y):
        # y[0] = vapor mixing ratio
        # y[1] = ice mixing ratio
        # y[2:nbice-1] - ice particle radii

        if (int(t) > self.tmax):
            t = self.tmax

        temp = self.T[int(t)]  # K
        press = self.p[int(t)]  # Pa
        wallflux = self.wallflux[int(t)]

        a = self.a
        c = self.c

        # a = self.rice
        # c = self.rice
        alpha_a = self.alpha_a
        alpha_c = self.alpha_c

        nIceBinsUsed = self.nIceBinsUsed

        derivVec = np.zeros(2 + self.nbice)

        # use same constants as rest of codes
        eps = constants.eps
        R = constants.R
        Rd = constants.RA
        Rv = constants.RV
        Mw = constants.mw
        Ma = constants.ma
        Ls = constants.LS
        Cp = constants.CP
        alf_T = constants.ALPHA_THERM_ICE
        rho_i = constants.RHOICE
        To = constants.To

        ed = (y[0] / eps) * press  # Partial pressure of water vapor. (Pa)
        esid = e_si(temp, self.useGG)  # Partial pressure of vapor at ice saturation. (Pa)
        ssi = (ed / esid) - 1.0  # Supersaturation over ice.
        Rm = (1.0 + (y[0] / eps)) / (1.0 + y[0]) * Rd  # Gas constant for moist air.
        rho_air = press / (Rd * temp)  # Density of air. (kg/m3)
        delta = 6.6e-8 * (101325.0 * temp) / (273.15 * press)  # Mean free path. (m)

        # Mean molecular speeds.
        vv = np.sqrt((8.0 * R * temp) / (np.pi * Mw))
        va = np.sqrt((8.0 * R * temp) / (np.pi * Ma))
        #
        Dv = 0.211 * ((temp / 273.15) ** 1.94) * (101325.0 / press) * 1.0e-4  # Vapor diffusivity (m2/s) P=K 13-3
        Kt = (5.69 + 0.017 * (temp - 273.15)) * 418.684 / 1.0e5  # Thermal diffusivity

        # Specific latent heat of vaporization of water (J/kg) from Equation (15.3), Page 778 of S&P.
        Lv = 2.5e6 * (273.15 / temp) ** (0.167 + 3.67e-4 * temp)

        # Specific latent heat of fusion of water (J/kg) from Equation (15.4), Page 778 of S&P.
        Lf = 0.3337e6 + 2031.0 * (temp - To) - 10.467 * (temp - To) ** 2
        Ls = Lv + Lf  # Specific latent heat of sublimation of ice.

        # Calculate radial growth of ice particles.
        caps = vecCapacitance(a[:nIceBinsUsed], c[:nIceBinsUsed])
        capDs = vecCapacitance(a[:nIceBinsUsed] + delta, c[:nIceBinsUsed] + delta)

        Dvp = Dv * (((2.0 / 3.0) * (
                (4.0 * Dv * caps) / (alpha_a[:nIceBinsUsed] * vv * a[:nIceBinsUsed] * c[:nIceBinsUsed]) + (
                caps / capDs)) ** -1) \
                    + ((1.0 / 3.0) * ((4.0 * Dv * caps) / (alpha_c[:nIceBinsUsed] * vv * a[:nIceBinsUsed] ** 2) + (
                        caps / capDs)) ** -1))
        Ktp = Kt * (((2.0 / 3.0) * (
                (4.0 * Kt * caps) / (alf_T * rho_air * Cp * va * a[:nIceBinsUsed] * c[:nIceBinsUsed]) + (
                caps / capDs)) ** -1) \
                    + ((1.0 / 3.0) * ((4.0 * Kt * caps) / (alf_T * rho_air * Cp * va * a[:nIceBinsUsed] ** 2) + (
                        caps / capDs)) ** -1))

        Gsph = ((Rv * temp) / (Dv * esid) + (Ls / (Kt * temp)) * (Ls / (Rv * temp) - 1.0)) ** -1
        rs = y[2:nIceBinsUsed + 2]

        if (self.capmodel == True) or (ssi < 0.0) or (len(rs) == 0):
            Gi = Gsph  # ((Rv * temp) / (Dv * esid) + (Ls / (Kt * temp)) * (Ls / (Rv * temp) - 1.0)) ** -1
        elif (self.newG is not None):
            Si = (ssi + 1.0) * np.ones(rs.shape[0])
            Gi = self.newG.gfunction(rs, Si, temp, Gsph)
        else:  # kinetic model
            Gi = ((Rv * temp) / (Dvp * esid) + (Ls / (Ktp * temp)) * (Ls / (Rv * temp) - 1.0)) ** -1
            # print(Gi[0:10])
        epsilon = 1e-12
        derivVec[2:2 + nIceBinsUsed] = (caps * Gi * ssi) / (
                    rho_i * y[2:nIceBinsUsed + 2] ** 2)  # *labConfig.mdotsel[2:2 + nIceBinsUsed]

        # add limiter here for cases where the derivVec[2:2+nIceBinsUsed]+y[2:nIceBinsUsed+2]<0.0
        idx = np.where(derivVec[2:2 + nIceBinsUsed] + y[2:nIceBinsUsed + 2] < 0.0)

        if len(idx) > 0:
            derivVec[idx[0] + 2] = -1 * y[idx[0] + 2]  # check this?
            # derivVec[idx[0] + 2] = 0.0

        derivVec[1] = np.sum(4.0 * np.pi * self.Nice[0:nIceBinsUsed] * y[2:nIceBinsUsed + 2] ** 2 * rho_i * derivVec[
                                                                                                            2:2 + nIceBinsUsed])  # kg/m3

        derivVec[1] = derivVec[1] / rho_air  # kg/kg

        # dqv/dt
        # change in vapor mixing ratio (enforce mass conservation).
        # wallflux = 0.0
        derivVec[0] = -1 * derivVec[1] + wallflux

        return derivVec

    def getaida_conditions(self, expnum):
        # AIDA expnum
        inputs = loadaidainputs(expnum)
        inputs['dvap_flux'] = inputs['dvap_flux'] / 1e9

        # set up the AIDA temperature and presssure
        self.cn_ice = inputs['cn_ice'].values * 1e6  # per m3
        self.p = inputs['p_pa'].values  # Pa
        self.T = inputs['tg_k'].values  # K
        self.wallflux = inputs['dvap_flux'].values  # ppmv

        # update the number of points in case it is shorter than 1200
        self.tmax = len(self.cn_ice) - 1  # Maximum time [s].
        self.npts = int(self.tmax / self.dt)  # Number of time steps.

    def initialize_vector(self, expnum):
        # get RH
        isodat = loadinitialcond()

        T = self.T[0]
        P = self.p[0]
        initRice = isodat[isodat['expnum'] == expnum]['initRI'].values[0] / 100.0

        Rd = constants.RA
        Rv = constants.RV

        # check this!!!
        e = initRice * e_si(T, self.useGG)  # partial pressure of water vapor (Pa) determined from initial Si
        rho_v = e / (Rv * T)  # kg/m3
        rhoAir = P / (Rd * T)  # kg/m3
        qv = rho_v / rhoAir  # kg/kg

        IC = np.zeros(2 + self.nbice)
        IC[0] = qv
        IC[1] = 0.0

        return IC, initRice

    def timeloop(self, expnum):
        # this gets the experimental data for the right AIDA experiment
        self.getaida_conditions(expnum)
        Rd = constants.RA
        Rv = constants.RV
        eps = constants.eps
        # this gets the initial conditions for qv, qi
        ICs, initRice = self.initialize_vector(expnum)

        time = [float(i) * self.dt for i in range(self.npts + 1)]

        #  and the ode solver.
        atols = [1.0e-17 for _ in range(2 + self.nbice)]
        # r = ode(self.dydt, jac=None).set_integrator('vode', method='bdf', rtol=1.0e-5, atol=atols)
        atols = 1.0e-17
        r = ode(self.dydt, jac=None).set_integrator('dopri5', rtol=1.0e-9, atol=atols)

        npts = self.npts
        if (self.printtimes == True):
            print("Initial conditions (qv,qi,npts): ", ICs[0:2], npts)

        # Output arrays.
        # time = np.zeros(npts+1)
        qv_out = np.zeros(npts + 1)
        qi_out = np.zeros(npts + 1)
        si_out = np.zeros(npts + 1)

        a_out = np.zeros(npts + 1)
        c_out = np.zeros(npts + 1)
        ri_out = np.zeros(npts + 1)
        rhoAir = np.zeros(npts + 1)
        integratedIce = np.zeros(npts + 1)
        resultout = np.zeros((npts + 1, self.nbice + 2))

        si_out[0] = initRice
        qv_out[0] = ICs[0]
        qi_out[0] = ICs[1]
        rhoAir = self.p / (Rd * self.T)

        vf = np.zeros(self.nbice)
        phif = np.zeros(self.nbice)
        gamma = np.zeros(self.nbice)

        start = clock.time()

        # Time loop.
        for i in range(1, npts - 1):
            # labConfig.mdotsel = getMdotselValues(si_out[i-1], self.T[i-1], self.nbice, randomCdf, dsir, labCdf, mrattab)

            # nucleate any ice at this time step
            self.nucleation(i, si_out[i - 1])
            nIceBinsUsed = self.nIceBinsUsed
            if (i % 100 == 0) and (self.printtimes == True):
                print(i, nIceBinsUsed, np.sum(self.Nice), time[i - 1], time[i])
                # print(time[i-1],time[i])

            for j in range(nIceBinsUsed):
                ICs[j + 2] = self.rice[j]

            sca = self.sca
            scc = self.scc

            # ee = si_out[i-1] * e_si(self.T[i-1],self.useGG)
            si = si_out[i - 1]  # ee/e_si(self.T[i-1]+To, self.useGG) - 1.0

            for j in range(self.nIceBinsUsed):
                # print(self.T[i-1]+To,100.0*self.p[i-1],si,sca,scc,self.a[j],self.c[j],self.m)
                self.slocal_a[j], self.slocal_c[j], self.alpha_a[j], self.alpha_c[j] = getDepCoeffs(self.T[i - 1],
                                                                                                    100.0 * self.p[
                                                                                                        i - 1],
                                                                                                    si, sca, scc,
                                                                                                    self.a[j],
                                                                                                    self.c[j], self.m)

            gamma = self.alpha_c[:nIceBinsUsed] / self.alpha_a[:nIceBinsUsed]

            r.set_initial_value(ICs, time[i - 1])
            # print(ICs.shape)
            result = r.integrate(time[i])
            #
            # Don't let solver produce negative ice mixing ratio.
            result[1] = max(0.0, result[1])

            qv_out[i] = result[0]  # kg/kg
            qi_out[i] = result[1]  # kg/kg

            # eps (Mw/Ma)
            e = (result[0] / eps) * self.p[i]

            esi = e_si(self.T[i], self.useGG)

            si_out[i] = e / esi

            # Average ice particle radius.
            rsum = 0.0
            totalIce = 0.0

            epsilon = 0.1e-6  # A really teeny ice radius.

            for k in range(self.nIceBinsUsed):
                if (result[k + 2] > epsilon):
                    # result[k+2]=result[k+2]
                    if (result[k + 2] < self.rice[k] * 10):
                        result[k + 2] = result[k + 2]
                    else:
                        result[k + 2] = self.rice[k]
                else:  # Remove particles smaller than threshold value.
                    result[k + 2] = epsilon
                    self.Nice[k] = 0.0

                self.rice[k] = result[k + 2]
                totalIce += self.Nice[k]
                # rsum += result[k+2] * self.Nice[k]
                rsum += self.rice[k] * self.Nice[k]

            if (totalIce > 0.0):  # Avoid divide-by-zero problems.
                ri_out[i] = (rsum / totalIce) * 1.0e6  # convert to um
                # Remove ice across all bins based on number concentration from AIDA experiments ...
                frac = self.cn_ice[i] / totalIce
                for k in range(self.nIceBinsUsed):
                    self.Nice[k] = self.Nice[k] * frac
                #   and adjust the mixing ratios to account for the removal of ice.
                result[0] = result[0] + (1 - frac) * result[1]  # vapor
                result[1] = frac * result[1]  # ice

            integratedIce[i] = np.sum(self.Nice)  # *rhoAir[i]
            resultout[i, :] = result
            ICs = np.copy(result)

            # Volumes of spherical ice particles following time step.
            vf = (4.0 / 3.0) * np.pi * self.rice[:nIceBinsUsed] ** 3

            phi = self.phi[:nIceBinsUsed]
            v = self.v[:nIceBinsUsed]

            phif = phi * (vf[:nIceBinsUsed] / v) ** (
                    (gamma[:nIceBinsUsed] / phi - 1.0) / (gamma[:nIceBinsUsed] / phi + 2.0))
            self.a[:nIceBinsUsed] = (0.75 * vf[:nIceBinsUsed] / (np.pi * phif[:nIceBinsUsed])) ** (1.0 / 3.0)
            self.c[:nIceBinsUsed] = phif[:nIceBinsUsed] * self.a[:nIceBinsUsed]
            # self.a[:nIceBinsUsed] = self.rice[:nIceBinsUsed] #(0.75 * vf[:nIceBinsUsed]/(np.pi))**(1.0/3.0)
            # self.c[:nIceBinsUsed] = self.rice[:nIceBinsUsed] #self.a[:nIceBinsUsed]
            self.v[:nIceBinsUsed] = vf[:nIceBinsUsed]
            self.phi[:nIceBinsUsed] = phif[:nIceBinsUsed]

            # Save ice distribution.
            if (integratedIce[i] > 0.0 and labConfig.saveDists):
                fileName = distributionsDir + 'dist_' + str(i).zfill(4) + '.dat'
                with open(fileName, 'w') as f:
                    # f.write('%4d %d %e %e\n' % (nIceBinsUsed, self.nbice, si_out[i], labConfig.suiratio))
                    f.write('%4d %d %e\n' % (nIceBinsUsed, self.nbice, si_out[i]))
                    for bin in range(self.nbice):
                        f.write('%4d %e %e %e %e \n' % (bin, self.rice[bin], self.Nice[bin], self.a[bin], self.c[bin]))

            # Calculate average a- and c-axis lenths (in microns).
            asum = 0.0
            csum = 0.0
            totalIce = 0.0
            for k in range(self.nbice):
                totalIce += self.Nice[k]
                asum += self.a[k] * self.Nice[k]
                csum += self.c[k] * self.Nice[k]
            if (totalIce > 0.0):
                a_out[i] = (asum / totalIce) * 1.0e6
                c_out[i] = (csum / totalIce) * 1.0e6
        stop = clock.time()

        print("Experiment ", expnum, ' Elapsed time: %4.2f seconds' % (stop - start))

        if (self.printtimes == True):
            print(self.nIceBinsUsed, 'of', self.nbice, 'ice bins used.')
        # print(qi_out.shape,rhoAir.shape)
        IWC = qi_out * 1e6

        return time, qv_out, si_out, ri_out, a_out, c_out, integratedIce, IWC, self.T, self.p, qi_out, resultout, nIceBinsUsed